// This file is automatically generated by the Firebase setup
// Do not edit this file manually

// This is a placeholder for the Firebase config
// The actual config will be injected by the build process
const firebaseConfig = {
  apiKey: "SET_UP_A_FIREBASE_PROJECT",
  authDomain: "SET_UP_A_FIREBASE_PROJECT",
  projectId: "SET_UP_A_FIREBASE_PROJECT",
  storageBucket: "SET_UP_A_FIREBASE_PROJECT",
  messagingSenderId: "SET_UP_A_FIREBASE_PROJECT",
  appId: "SET_UP_A_FIREBASE_PROJECT",
  measurementId: "SET_UP_A_FIREBASE_PROJECT"
};

export default firebaseConfig;
